### ISSUE TITLE
apply for task( screenshot 11 prototype)

### ISSUE THREAD

**Issue by mo3ni** [Hudhud/Job_Bazaar#43]
- [x] Title ( by category), close button

- [x] Category image , hourly rate

- [x] Text area ( Description, location, date) 

- [x] interested checkbox 
* maybe should be able to send a notification to job announcer 

- [x] more info alert

**Comment by atila29** [comment]
Have looked at the issue, and created a screen with navigation. would like to hear feedback and how to proceed.
